### ISSUE TITLE
Missing ITEM ID

### ISSUE THREAD

**Issue by pqvindesland** [moudsen/mailGraph#20]
Hi 

I am using Zabbix 5.0.12 if i run php mailGraph.php test then I get error: 

Missing ITEM ID? and zabbix says : MailGraph notification failed : SyntaxError: invalid json (at offset 1)

Do you know what the issue is?

Regards
Per

**Comment by moudsen** [comment]
Hi,
Can you please goto the config directory and run:

`php config.php config.json list`

Can you let me know if you get an error here or if it displays all configured values in the JSON?

**Comment by moudsen** [comment]
If the above works (not a JSON formatting issue and all values are shown):
Did you follow https://github.com/moudsen/mailGraph/wiki/8--Troubleshooting as you need to fill in the CLI_<attribute> information before you can actually start a manual test?!?

**Comment by pqvindesland** [comment]
Hi

Many thanks for looking into this, 

Is this error normal: 
2021-07-05 17:03:45 : !! (8) "Undefined index: HTTPPRoxy" at line #468 of "/usr/share/zabbix/mailGraph.php"
PHP Notice:  Undefined index: HTTPPRoxy in /usr/share/zabbix/mailGraph.php on line 468

The output of php config.php config.json list looks ok to me.
  "script_baseurl" => "http://zabbix.flir.net/"
  "cli_itemId" => "2295327"
  "cli_triggerId" => "26668"
  "cli_eventId" => "2285397"
  "cli_duration" => "0"
  "cli_recipient" => "zabbix@flir.net"
  "cli_subject" => "[TEST] {{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}"
  "cli_baseURL" => "http://zabbix.flir.net/zabbix/"
  "cli_period" => "30m"
  "cli_period_header" => "Last 30 minutes"
  "cli_debug" => "1"
  "cli_proxy" => ""
  "zabbix_user" => "Admin"
  "zabbix_user_pwd" => "password"
  "zabbix_api_user" => "Admin"
  "zabbix_api_pwd" => "password"
  "mail_from" => "zabbix@flir.net"
  "subject" => "{{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}"
  "smtp_server" => "smtp.flir.net"
  "smtp_port" => "25"
  "smtp_transport" => "none"
  "smtp_strict" => "no"
  "graph_match" => "any"
  "period" => "20m"
  "period_header" => "Last 20 minutes"
  "debug" => "0"

root@zabbix:/usr/share/zabbix# php mailGraph.php test
2021-07-05 17:03:45 : # Data passed to MailGraph main routine and used for processing
{
    "itemId": 2295327,
    "eventId": 2285397,
    "recipient": "zabbix@flir.net",
    "baseURL": "http:\/\/zabbix.flir.net\/zabbix\/",
    "duration": 0,
    "subject": "[TEST] {{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}",
    "period": "30m",
    "period_header": "Last 30 minutes",
    "debug": 1,
    "HTTPProxy": ""
}
2021-07-05 17:03:45 : !! (8) "Undefined index: HTTPPRoxy" at line #468 of "/usr/share/zabbix/mailGraph.php"
PHP Notice:  Undefined index: HTTPPRoxy in /usr/share/zabbix/mailGraph.php on line 468
2021-07-05 17:03:45 : # LOGIN to Zabbix
2021-07-05 17:03:45 : % postJSON: http://zabbix.flir.net/zabbix/api_jsonrpc.php
2021-07-05 17:03:45 : > POST data: {"jsonrpc":"2.0","method":"user.login","params":{"user":"<masked>","password":"<masked>"},"id":1,"auth":null}
2021-07-05 17:03:45 : > Received 0 bytes
Error logging in to Zabbix? (http://zabbix.flir.net/zabbix/api_jsonrpc.php)

**Comment by moudsen** [comment]
Can I ask what your version is of mailGraph? You can look it up in the top of mailGraph.php ...

**Comment by pqvindesland** [comment]
Yep sure, it looks like 1.28 

 1.28 2021/03/24 - Mark Oudsen - Added ability to specify username/password for TLS/SSL 

That's the last entry

**Comment by moudsen** [comment]
Can you please pick up v1.29? I've added a lot of checks and fixed a lot of bugs compared to v1.28. I can also remember having this bug specifcally. Just replace mailGraph.php in your case - should work.

**Comment by pqvindesland** [comment]
When Zabbix is trying to execute it fails with error:
MailGraph notification failed : TypeError: undefined not callable (property 'setProxy' of [object Object])

I forgot to mention that it runs on a Ubuntu 20.04 machine, I checked the logs but

I changed it to the new file and the ouput is now:

/usr/share/zabbix# php mailGraph.php test
2021-07-06 14:10:57 : <<< mailGraph v1.29 >>>
2021-07-06 14:10:57 : # Invoked from CLI
2021-07-06 14:10:57 : # Data passed to MailGraph main routine and used for processing
{
    "itemId": 2295327,
    "eventId": 2285397,
    "recipient": "zabbix@flir.net",
    "baseURL": "http:\/\/zabbix.flir.net\/zabbix\/",
    "duration": 0,
    "subject": "[TEST] {{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}",
    "period": "30m",
    "period_header": "Last 30 minutes",
    "debug": 1,
    "HTTPProxy": ""
}
2021-07-06 14:10:57 : !! (8) "Undefined index: HTTPPRoxy" at line #473 of "/usr/share/zabbix/mailGraph.php"
PHP Notice:  Undefined index: HTTPPRoxy in /usr/share/zabbix/mailGraph.php on line 473
2021-07-06 14:10:57 : # LOGIN to Zabbix
2021-07-06 14:10:57 : % postJSON: http://zabbix.flir.net/zabbix/api_jsonrpc.php
2021-07-06 14:10:57 : > Received 68 bytes
2021-07-06 14:10:57 : > Token = 892c1279f39873bc4c764af7d4919d6a
2021-07-06 14:10:57 : # Retreiving EVENT information
2021-07-06 14:10:57 : % postJSON: http://zabbix.flir.net/zabbix/api_jsonrpc.php
2021-07-06 14:10:57 : > Received 960 bytes
2021-07-06 14:10:57 : > Event data
{
    "jsonrpc": 2,
    "result": [
        {
            "eventid": 2285397,
            "source": 0,
            "object": 0,
            "objectid": 25595,
            "clock": 1625481095,
            "value": 1,
            "acknowledged": 0,
            "ns": 524990030,
            "name": "High swap space usage ( less than 50% free)",
            "severity": 2,
            "r_eventid": 0,
            "c_eventid": 0,
            "correlationid": 0,
            "userid": 0,
            "opdata": "Free: 0 %, total: 2 GB",
            "relatedObject": {
                "triggerid": 25595,
                "expression": "{35432}<{$SWAP.PFREE.MIN.WARN} and {35433}>0",
                "description": "High swap space usage ( less than {$SWAP.PFREE.MIN.WARN}% free)",
                "url": "",
                "status": 0,
                "value": 1,
                "priority": 2,
                "lastchange": 1625481095,
                "comments": "This trigger is ignored, if there is no swap configured",
                "error": "",
                "templateid": 16051,
                "type": 0,
                "state": 0,
                "flags": 0,
                "recovery_mode": 0,
                "recovery_expression": "",
                "correlation_mode": 0,
                "correlation_tag": "",
                "manual_close": 0,
                "opdata": "Free: {ITEM.LASTVALUE1}, total: {ITEM.LASTVALUE2}",
                "discover": 0
            },
            "suppression_data": [],
            "suppressed": 0,
            "urls": []
        }
    ],
    "id": 2
}
2021-07-06 14:10:57 : # Retrieve TRIGGER information
2021-07-06 14:10:57 : % postJSON: http://zabbix.flir.net/zabbix/api_jsonrpc.php
2021-07-06 14:10:57 : > Received 803 bytes
2021-07-06 14:10:57 : > Trigger data
{
    "jsonrpc": 2,
    "result": [
        {
            "triggerid": 25595,
            "expression": "{35432}<{$SWAP.PFREE.MIN.WARN} and {35433}>0",
            "description": "High swap space usage ( less than {$SWAP.PFREE.MIN.WARN}% free)",
            "url": "",
            "status": 0,
            "value": 1,
            "priority": 2,
            "lastchange": 1625481095,
            "comments": "This trigger is ignored, if there is no swap configured",
            "error": "",
            "templateid": 16051,
            "type": 0,
            "state": 0,
            "flags": 0,
            "recovery_mode": 0,
            "recovery_expression": "",
            "correlation_mode": 0,
            "correlation_tag": "",
            "manual_close": 0,
            "opdata": "Free: {ITEM.LASTVALUE1}, total: {ITEM.LASTVALUE2}",
            "discover": 0,
            "functions": [
                {
                    "functionid": 35432,
                    "itemid": 51515,
                    "triggerid": 25595,
                    "parameter": "5m",
                    "function": "min"
                },
                {
                    "functionid": 35433,
                    "itemid": 51516,
                    "triggerid": 25595,
                    "parameter": "",
                    "function": "last"
                }
            ],
            "tags": []
        }
    ],
    "id": 3
}
2021-07-06 14:10:57 : # Retrieve ITEM information
2021-07-06 14:10:57 : % postJSON: http://zabbix.flir.net/zabbix/api_jsonrpc.php
2021-07-06 14:10:57 : > Received 36 bytes
2021-07-06 14:10:57 : > Item data
{
    "jsonrpc": 2,
    "result": [],
    "id": 4
}
! No response data received?

**Comment by moudsen** [comment]
The PHP is working fine, it's now something that has to do with the javascript coding. My suspicion is that you have an old version of that script in Zabbix.
Can you please go to Administration => Media Types => mailGraph and check if the "Script" is actually the one from https://github.com/moudsen/mailGraph/blob/main/javascript/zabbix.mailGraph.js or just copy that script into the "Script" field (open up the Editor for that at the right hand side)?
Based on you feedback I may consider to create a "mailGraph-installer" to ensure the configuration is set correctly.
Let me know if this fixes your issue as the rest of the config seems to work just fine.
The reason why Zabbix say "No response data received?" is that the error message gets in the way of the result ...

**Comment by moudsen** [comment]
I've added a new screenshot for your convenience https://github.com/moudsen/mailGraph/blob/main/images/Example-Zabbix-MediaType-Config.png to show how the Media Type configuration could look like.
It also shows the "Script" section and the editor of it at the right hand side of the row.

**Comment by moudsen** [comment]
Considering fully automation configuration/check to avoid version differences and smooth updates/upgrades. Needs some investigation into Zabbix API to figure on Media Types.

**Comment by pqvindesland** [comment]
Great many thanks, that worked, I copied the JS code in as in replacing what was there and that solved the issue.

Now I need to figure out the look and slap a company logo on it :)

**Comment by pqvindesland** [comment]
Actually two more questions before I leave you alone :) 

Is it possible to add html code to the messages, or can I add a link to a image?
Also a direct link to the problem page something like this https://zabbix.flir.net/zabbix/zabbix.php?action=problem.view&amp;filter_hostids%5B%5D={HOST.ID}&amp;filter_set=1 if it's even in a html code.

**Comment by moudsen** [comment]
Glad I could assist you to make this work.

The power of the usage of templates allows you to add almost anything according to your wishes! Have a look at /templates/html.template and observe the usage of plain HTML in combination with TWIG instructions.
Details are explained at https://github.com/moudsen/mailGraph/wiki/5--Templates where I've also documented the currently available variables that are generated within the code.

You should be able to easily pop in a logo in this code (just add HTML and upload/reference your image somewhere) or design a totally new template to your wishes (with a little help of the example code provisioned). Note the usage of FOR statements to loop through images generated by the mailGraph code.

This was one of my major challenges in the past I've tried to resolve with mailGraph as the Zabbix macros where not able to offer me the flexibility of building such structured templates ...

Although a straight URL for the requested problem view does not exist as a {{ PROBLEM_URL }} you can actually generate the URL by replace the {HOST.ID} with {{ HOST_ID }} in your URL like https://zabbix.flir.net/zabbix/zabbix.php?action=problem.view&amp;filter_hostids%5B%5D={{ HOST_ID }}&amp;filter_set=1 and to put this code in the html.template file where you want to add the reference.

Note that the HTML code at Zabbix side within the Media Type is not used at all as only for reporting purposes within Zabbix (like an event overview page where you can actually observe the Media code output as well).

Please let me know if this works for you, otherwise happy to extend the code to your needs ...

**Comment by moudsen** [comment]
You've also helped me discover a bug in my code: in your version of the code at line 473 there is a typo in mailGraph.php where HTTPPRoxy should be HTTPProxy (notice the capital **R** that should be a regular **r**).

You can either pick up my changed mailGraph.php code I've added just now, or replace the code yourself by changing the capital R.

That should fix the warning you are getting when executing on the CLI?
Cheers!

**Comment by moudsen** [comment]
PS: If you have ideas on anything you would like to see added to this work, just raise a new ticket and I will look into it!

**Comment by pqvindesland** [comment]
Many thanks again for all your assistance, I added the logo html link to the html.template file, so it looks good.

A direct link to each hosts problem page would be really useful, I have added it to the html.template file, since we have many thousand of instances that's monitored, so for a user it's really handy to have a link in the notification email without having to open up the web browser and locate the host in the zabbix page and then find the problem.

**Comment by moudsen** [comment]
So would you like to have a {{ HOST_PROBLEM_URL }} to point to exactly this page?

Once last hint for housekeeping (generating new code as we speak to deal with this): images generated under images/ are not automatically cleaned out. The idea was to allow for PLAIN messages to contain links to the images for users without HTML capability.

Can I ask you if you would use such a function or if a "AUTOCLEAN" option would be appreciated to clean up generated images after these have been generated? Also considering that images are not erased when in debug/CLI test mode for troubleshooting purposes ...

A simple crontab could do the same but just thinking out loud that not deleting the images afterwards may clog a system quite fast.

Share your 2 cents with me please as I will develop and test this on very short term (few days).

**Comment by moudsen** [comment]
Can you think of more easy Zabbix references besides the one identified?
First thought: {{ HOST_PROBLEM_LIST_URL }} for getting on the problems list page of Zabbix.
Please bring more forward as you see fit.
I can also commit to assist you in any other findings to allow my code to go into v2.00 stable and enterprise level readiness.

**Comment by moudsen** [comment]
Working on v1.30

**Done**
- {{ HOST_PROBLEMS_URL }} implemented & tested (running live in my environment)
- Removal of images implemented & tested (running live in my environment)

**Next**
- Image cleaning (older than X days)
- Log cleaning (older than X days)

If you are quick enough I can add some more into this version ... :-)

**Comment by pqvindesland** [comment]
Sorry for the delay in responding, it's a busy week.

The {{ HOST_PROBLEMS_URL }} is really just a must for us, I have added it to our configuration but a (official) configuration would be great,  all of the maintenance suggestions sounds great, it's something that we would really appricate.

I don't have any more suggestions for the moment, but I am pretty sure when some of our more (detail) oriented admins starts using it that they will have requests, I will ping you as I get them in.

Regards
Per

**Comment by moudsen** [comment]
Ok. I will most likely release v1.30 this weekend (including the retention options) after succesfull testing in my own live environment and will inform you here when that's been done. Once released I will notify you here, close this ticket and would like to request you to open new tickets, preferable per each topic where you have issues or feel the need for a new feature.
Cheers!

PS: {{ HOST_PROBLEMS_URL }} works like a charm in my environment :-).

**Comment by moudsen** [comment]
Code has been running succesfully in my own environment - publishing on short notice (this week).

**Comment by moudsen** [comment]
Code release in v1.30 has to wait - there was no more time just before my holiday ...
Will release most likely around last week of August latest.

**Comment by moudsen** [comment]
Back on line and picking up on next version very soon. Apologies for the delay due to personal circumstances ...

**Comment by moudsen** [comment]
Just to let you know I've released v1.31. Let me know how mailGraph performs in your environment and how I could further assist/enhance the code.

**Comment by moudsen** [comment]
Just to let you know I've released v2.x that fixes any problems with ItemID as per Zabbix 5.4+ the ItemID is no longer always publicated from Zabbix side. I've decided to switch to pick up the ItemID from the first trigger function, also considering to pick up all items from all functions, but need some more data and design work to see if that would bring further benefits.

I'm closing this issue now as it was purely v1.x related. If you have any issues with v2.x please let me know and I'll dive into it!
