### ISSUE TITLE
Notification email 

### ISSUE THREAD

**Issue by pqvindesland** [moudsen/mailGraph#21]
Hi 

We're wondering if it is possible to have a bar around the email ( have attached a screenshot of what i mean) 

The idea behind it is that the frame changes colour to the severity so disaster gets the same colour, meaning it replaces the blue colour that's on the screenshot.

It would help a sysadmin easily prioritise the work and also have a simple way of seeing what has happen, who has been notified and who to contact.

Regards
Per

![notification email](https://user-images.githubusercontent.com/18611311/126513687-ff32d641-2b06-4173-ad71-0df2a807b80a.png)

**Comment by moudsen** [comment]
Hi Per,

Yes that is possible.

The beauty of using templates is that someone with HTML and CSS knowledge while using the TWIG variables can turn any message into something as beautiful or shaped (or not) as you want to have it.

The provded HTML template under /templates gives a good example to how achieve that as the current e-mails sent color based on their resolution state (out of the box).

Do you have someone available with HTML knowledge (specifically CSS) to build that form for you? Using the TWIG parsing and variables passed to the form you can have something that switches color based on about anything as long as it is from a static list (like notification, warning, error, critical).
Unfortunately I do not have the time to develop this form together with you ...

The Graphs section is fine (re-use the current TWIG code for that).

The distribution list is trickier as per each notification the process is triggered individually. Do you want me to pick up a list of all people that this message has been sent to from the associated ACTION in Zabbix? It is possible, but not on short term.

For the Support information: can you give me a hint where you register this information in Zabbix? (for example in Tags or in Inventory on HOST or TRIGGER level?) That could make it into my next release for tomorrow (if you're quick enough in your response :-)).

Regards, Mark

**Comment by pqvindesland** [comment]
Hi Mark

We don't have the support information in (yet) it will come at some stage, but for the moment we are busy pushing Zabbix to the EMEA sites, which is taking most of my time.

I was thinking that the distribution list will be to who is has been sent to, that would help when or if a second reminder was sent out as more team members and managers will be added to the list, that way everyone has a good visibility in who was notified and when.

I will see if I can find someone with CSS skills, I'm in the same boat, I got no time to do it. 

Regards
Per

**Comment by moudsen** [comment]
Hi Per,

Understood. I will wait until you have made a choice where you will store the data and will develop code at my end to make that work.

For the distribution list part: I have looked it up and believe I can retrieve all people attached to a message group. Not sure what you mean by "more team members and managers" but if they have access and are passed the mail message they can use the links within the message to go into the right host, problem, etc.

Keep me informed on your progress.

Regards, Mark

PS: I am on holiday for a few weeks ... :-)

**Comment by moudsen** [comment]
Hi Per,

Any news on this topic you can share with me? Have you discussed/decided on the message group?

Regards, Mark

**Comment by pqvindesland** [comment]
Hi Mark

Apologies for the delay in replying, but it's a busy period.

We sort of a left it as it it, I have a dev that will eventually look into it but he hasn't had the time also and it's not really a priority for us, it's a cosmetic thing which always lands at the end of the priority list.

But we are using Magraph now for all sites, which is almost every country you can think of and it's working really well, I haven't bothered updating to the latest version but i might do it later this year if time permits.

Regards
Per

**Comment by moudsen** [comment]
Hi Per,

Please keep an eye on my updates - I've just released v2.x of mailGraph.php to facilitate a major change in Zabbix 5.4 (no more Screens, all Dashboards now) and have also found that "ItemID" is no longer always provisioned by Zabbix 5.4 anymore (now picking up the item ID from the first trigger function, restoring the functionality easily).

Note that not replacing the code will degrade its functionality, especially when moving into Zabbix 5.4+ (also noticed that beta Zabbiz 6 has also changed it's core function).

I'm also open now to new functional requests until end of Jan 2022.
If you have such requests, please raise a new issue here.

Kind regards, Mark
