### ISSUE TITLE
what is 'hostGraphs'?

### ISSUE THREAD

**Issue by qkrqkstm** [moudsen/mailGraph#25]
hello
I solved most of them.
It cannot proceed due to the message below.
What did I miss?

---
 2021-10-06 16:45:10 : > Received 12788 bytes 
 2021-10-06 16:45:10 : > Saved to /usr/share/zabbix/images/zabbix_graph_1880.1633506310-10m.png 
 2021-10-06 16:45:10 : !! (8) "Undefined variable: hostGraphs" at line #1185 of "/usr/share/zabbix/mailGraph.php" 
 2021-10-06 16:45:10 : !! (2) "sizeof(): Parameter must be an array or an object that implements Countable" at line #1185 of "/usr/share/zabbix/mailGraph.php" 
 2021-10-06 16:45:10 : # Setting up mailer
00:00:00.525 [Unknown] MailGraph notification failed : SyntaxError: invalid json (at offset 10)

**Comment by moudsen** [comment]
That means that there are no graphs associated to the corresponding host and item. You can either create a graph for the applicable item in a template or for that particular host, or you can direct mailGraph to use a different object to show the graphs for (by providing the graph id you wish to be attached).

Take a look at https://github.com/moudsen/mailGraph/wiki/6--MailGraph-logic to provide mailGraph with such pointers.

I will enhance the code to detect or suppress these messages and to provision a better explanation. Apologies for that.

Let me know if this works for you.

**Comment by moudsen** [comment]
Just checked something else on this point as I noticed the "invalid json" message at the bottom.
My bad as I recognize that on new installations the PHP error settings may be in the way (hence I produced an error capture routing to prevent this but still see any issues in the logs).
Please add the following after the DEBUG section in the top of the mailGraph.php code:

// Limit server level output errors

error_reporting(E_ERROR | E_PARSE);

That should fix it.
I will fix both the messages and the addition of the error reporting settings on very short notice and release an update for it.
Apologies for the inconvenience.

**Comment by moudsen** [comment]
The unsuppressed error message was passed to Zabbix hence the "json error".

**Comment by moudsen** [comment]
Just curious: can you share your version number of mailGraph here? You can find it in the top of the log or in the top of the code of mailGraph.php.

**Comment by moudsen** [comment]
Version v1.31 released. This should fix your problems. Please replace mailGraph.php with the new version. I'm curious to learn if this solves your problem.

**Comment by qkrqkstm** [comment]
hello,
The file 'mailGraph.php' has been updated to the latest version.
An error occurred during the media type test as follows.

00:00:00.000 [Debug] [MailGraph Webhook] Sending request: http://x.x.x.x/mailGraph.php?{"itemId":"36752","eventId":"43","recipient":"refine-mng","baseURL":"http://x.x.x.x/","duration":"0","graphWidth":"300","graphHeight":"120","subject":"test","showLegend":"1","periods":"10m","periods_headers":"Last 10 Minutes","debug":"1","infoTest":"Test"}
00:00:00.602 [Debug] [Mailgraph Webhook] Receiving response:null
00:00:00.602 [Unknown] MailGraph notification failed : TypeError: cannot read property 'errors' of null

The action log is as follows.
MailGraph notification failed : Error: cannot get URL: Timeout was reached

I'm always grateful.

**Comment by moudsen** [comment]
Hi, apologies for the late response. I was kept busy by my main job as Enterprise Architect in some deals.

The main code has been rewritten to facilitate a major change in Zabbix 5.4 as well as to fix some obvious issues that I did not catch earlier and from other feedback.

Can I ask you to upgrade the mailGraph.php to version 2.x? (no other changes were made, only the main code has changed).
I would like you to re-verify your issue with the new code.

Kind regards, Mark

**Comment by moudsen** [comment]
In case of further issues, please raise a new issue. Closing for now assuming al was sorted with the previous code updates.
