### ISSUE TITLE
To verify that mailGraph v2.02 works in Zabbix 6.0 LTS

### ISSUE THREAD

**Issue by moudsen** [moudsen/mailGraph#30]
With the release of Zabbix 6.0 LTS verification is required that mailGraph functions as expected.

**Comment by onurintel** [comment]
I have successfully migrated yerterday from Zabbix 4.4.10 (centos 7) to Zabbix 6.0 LTS (ubuntu 20).

First, I got an error because the php-curl module was not installed properly. (install : sudo apt-get install php-curl)

Secondly, I got an error that there is no "double quote" symbol in the password fields in the config.json file. (manual edit : config.json file)

It's currently running fine on Zabbix 6.0 LTS, I'll keep checking it for a while as it's still new.

Thx Moudsen

**Comment by moudsen** [comment]
Hi, thx for the update - I can confirm mailGraph works properly under Zabbix 6.0 LTS and will add the CURL dependency to the installation part on my wiki.
With regards to the double quotes: I'm digging into that coming weekend - definitely should not be the case! (perhaps I've forgotten to escape double quotes some where).
I'm also updating mailGraph shortly with some next steps on usage of certain tags to manipulate the output graphs/data to resolve the migration from Screens to Dashboards.
Finally I've also added retention periods for logs and graphs in the latest version to prevent any system of overflowing on disk usage.

Kind regards, Mark

**Comment by moudsen** [comment]
I've tried to reproduce the issue with the config.json regarding double quotes but was unable to.
Can you describe some steps how I can observe the issue at hand?

**Comment by moudsen** [comment]
Upgrade to 6.0.2 LTS completed on my environments. Now focussing on API changes between 5.x and 6.x and as well identifying the way forward to resolve the TAGging changes from Screens to Dashbaords with widgets.

**Comment by kntrbs76** [comment]
Hi. Thx for mailGraph!
zabbix 6.0 
Macro infoXXX does not work.
Add MailGraph Media type of which the name starts with 'infoConn' = {HOST.CONN}
Add html.tepmlate 
------------
Host; {{ HOST_NAME }} {{ infoConn }}
-------------
in email:
Host_name - YES
infoConn - NO

What am I doing wrong? thx

**Comment by moudsen** [comment]
> ## Hi. Thx for mailGraph!
> zabbix 6.0
> Macro infoXXX does not work.
> Add MailGraph Media type of which the name starts with 'infoConn' = {HOST.CONN}
> Add html.tepmlate
> ## Host; {{ HOST_NAME }} {{ infoConn }}
> in email: Host_name - YES infoConn - NO
> 
> What am I doing wrong? thx

Not sure why this is happening.

The best thing to do in such cases is to switch on the debug log which will write a log file in which you can read when and how the passed value was processed.

config.json:
 "debug": 1,

Looking at an actual dump file, search for "=== VALUES AVAILABLE FOR TWIG TEMPLATE ===" and check if the information has indeed been passed in the first place.

Let's take it from here?

If the issue persists, please create a new Issue and I will help you to get this working! This ticket was merely meant for Zabbix 6.0 functional testing which has completed at my end (now focussing on Zabbix 6.2 where some stuff actually has been changed in a princpal form - not the case for 6.0 :-)).

**Comment by moudsen** [comment]
All functionality confirmed working. Closing this ticket, now proceeding with Zabbix 6.2.
