### ISSUE TITLE
Can I use this for zabbix 4.0

### ISSUE THREAD

**Issue by vanimesh** [moudsen/mailGraph#31]
Hi..can I use this for zabbix 4.0? If yes can you please guide me with steps?

**Comment by moudsen** [comment]
Hi Vanimesh,

Apologies for the late response.

Based on the documentation from Zabbix the notification mechanism was way less evolved as per Zabbix 5.x (specifically the Javascript intermediate communications interface associated with the Webhook functionality) hence my careful conclusion is that without modification mailGraph will not function out-of-the-box in Zabbix 4.x.

I unfortunately do not have the time to setup/develop/test/maintain mailGraph for backwards compatibility with Zabbix 4.x.

Would you happen to know if there are more people looking for this functionality in Zabbix 4.x (LTS) as I've observed in the Zabbix 4.x source code that the other depending code is available?

That is besides the idea that Zabbix 4.0 LTS was retired last year and as per Oct 2023 the 4.0 version will no longer be maintained by the Zabbix core team. Definitely do not want to push you on upgrading (you may have very good reasons not to) but please understand from my end that I'm currently rather focussing on version 6.0 (LTS) updates (some very fundamental changes I can share with you) with the time available for it from my end.

Kind regards, Mark
