### ISSUE TITLE
00:00:00.138 [Unknown] MailGraph notification failed : SyntaxError: invalid json (at offset 1)

### ISSUE THREAD

**Issue by sjteoh111** [moudsen/mailGraph#33]
Hi,

I have follow all the steps , but when i test the media type it show the error below. How to solve this issue and i have no idea now.

![image](https://user-images.githubusercontent.com/115065492/201876354-7039c228-d9f0-4308-a14a-ef312e7c810c.png)

**Comment by sjteoh111** [comment]
CLI Manual Test and the result show no response and received ? i tried copy the java scripts but it not working as well , need your help on this. 


![image](https://user-images.githubusercontent.com/115065492/201875153-ae205fee-1e26-4042-883a-4813c527395c.png)

**Comment by moudsen** [comment]
Hi, apologies for the late response.
What version of Zabbix are you running as the hook says the API request came back empty?

**Comment by moudsen** [comment]
No response received. Closing.
