### ISSUE TITLE
Invalid parameter "/": unexpected parameter "user

### ISSUE THREAD

**Issue by pqvindesland** [moudsen/mailGraph#35]
Hi 

I am using Zabbix 6.4.3 and I seem to have hit a know change in Zabbix

When I run php mailGraph.php test it fails with Invalid parameter "/": unexpected parameter "user" it seems to be related to a change in Zabbix from version 6.4, there is more information here https://support.zabbix.com/browse/ZBXNEXT-8085

It is also discussed in other plugins like this one https://github.com/alexanderzobnin/grafana-zabbix/issues/1583 who also has a (hack) suggested, but it doesn't give a complete fix.

Would you be able to have a look into this?

Regards
Per

**Comment by pqvindesland** [comment]
Sorry I forgot to add in the output of php mailGraph.php test

# php mailGraph.php test
2023-06-09 07:18:02 : <<< mailGraph v2.020 >>>
2023-06-09 07:18:02 : # Invoked from CLI
2023-06-09 07:18:02 : # Data passed to MailGraph main routine and used for processing
{
    "itemId": 0,
    "eventId": 0,
    "recipient": “someone@company.no",
    "baseURL": "https:\/\/company.no\/zabbix\/",
    "duration": 0,
    "subject": "[TEST] {{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}",
    "periods": "10m,4h,2d,7d",
    "periods_headers": "Last 10 minutes,Last 4 hours,Last 2 days,Last 7 days",
    "debug": 1,
    "HTTPProxy": ""
}
2023-06-09 07:18:02 : # LOGIN to Zabbix
2023-06-09 07:18:02 : % postJSON: https://company.no/zabbix/api_jsonrpc.php
2023-06-09 07:18:02 : > POST data: {"jsonrpc":"2.0","method":"user.login","params":{"user":"<masked>","password":"<masked>"},"id":1,"auth":null}
2023-06-09 07:18:02 : > Received 141 bytes
Error logging in to Zabbix? (https://company.no/zabbix/api_jsonrpc.php):
array(5) {
  ["jsonrpc"]=>
  string(3) "2.0"
  ["method"]=>
  string(10) "user.login"
  ["params"]=>
  array(2) {
    ["user"]=>
    string(5) "admin"
    ["password"]=>
    string(15) “password”
  }
  ["id"]=>
  int(1)
  ["auth"]=>
  NULL
}

array(3) {
  ["jsonrpc"]=>
  string(3) "2.0"
  ["error"]=>
  array(3) {
    ["code"]=>
    int(-32602)
    ["message"]=>
    string(15) "Invalid params."
    ["data"]=>
    string(51) "Invalid parameter "/": unexpected parameter "user"."
  }
  ["id"]=>
  int(1)
}

**Comment by pqvindesland** [comment]
So I went for Zabbix  6.0.18 which is the current LTS and I am seeing some different errors, do you have any chance of looking at these?



Media type test log
00:00:00.000 [Debug] [MailGraph Webhook] Sending request: https://driftzabbix.intern.company.no/mailGraph.php?{"itemId":"{ITEM.ID}","eventId":"{EVENT.ID}","recipient":"{ALERT.SENDTO}","baseURL":"https://driftzabbix.intern.company.no/","duration":"{EVENT.DURATION}","graphWidth":"300","graphHeight":"120","subject":"{{ HOST_NAME|raw }}: ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}","showLegend":"0","periods":"10m,4h,1d,7d","periods_headers":"Last 10 minutes,Last 4 hours,Last day,Last 7 days","infoTest":"Test"}
00:00:00.781 [Debug] [Mailgraph Webhook] Receiving response:2023-06-28 12:10:48 : # Configuration taken from config.json { "script_baseurl": "https:\/\/driftzabbix.intern.company.no\/", "cli_itemId": 0, "cli_triggerId": 0, "cli_eventId": 0, "cli_duration": 0, "cli_recipient": "driftzabbix@company.no", "cli_subject": "[TEST] {{ HOST_NAME|raw }}: ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}", "cli_baseURL": "https:\/\/driftzabbix.intern.company.no\/zabbix\/", "cli_period": "30m", "cli_period_header": "Last 30 minutes", "cli_debug": 1, "cli_proxy": "", "zabbix_user": "<masked>", "zabbix_user_pwd": "<masked>", "zabbix_api_user": "<masked>", "zabbix_api_pwd": "<masked>", "mail_from": "driftzabbix@company.no", "subject": "{{ HOST_NAME|raw }}: ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}", "smtp_server": "localhost", "smtp_port": 25, "smtp_transport": "none", "smtp_strict": "yes", "graph_match": "any", "period": "20m", "period_header": "Last 20 minutes", "debug": 0 } 2023-06-28 12:10:48 : # Data passed to MailGraph main routine and used for processing { "itemId": "{ITEM.ID}", "eventId": "{EVENT.ID}", "recipient": "{ALERT.SENDTO}", "baseURL": "https:\/\/driftzabbix.intern.company.no\/", "duration": "{EVENT.DURATION}", "graphWidth": 300, "graphHeight": 120, "subject": "{{ HOST_NAME|raw }}: ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}", "showLegend": 0, "periods": "10m,4h,1d,7d", "periods_headers": "Last 10 minutes,Last 4 hours,Last day,Last 7 days", "infoTest": "Test" } 2023-06-28 12:10:48 : # LOGIN to Zabbix 2023-06-28 12:10:48 : % postJSON: https://driftzabbix.intern.company.no/api_jsonrpc.php 2023-06-28 12:10:48 : > POST data: {"jsonrpc":"2.0","method":"user.login","params":{"user":"<masked>","password":"<masked>"},"id":1,"auth":null} 2023-06-28 12:10:48 : > Received 68 bytes 2023-06-28 12:10:48 : > Token = 7d21a596c95cccc89acc4a1aea9ae27e 2023-06-28 12:10:48 : # Retreiving EVENT information 2023-06-28 12:10:48 : % postJSON: https://driftzabbix.intern.company.no/api_jsonrpc.php 2023-06-28 12:10:48 : > POST data: {"jsonrpc":"2.0","method":"event.get","params":{"eventids":0,"output":"extend","selectRelatedObject":"extend","selectSuppressionData":"extend"},"auth":"7d21a596c95cccc89acc4a1aea9ae27e","id":2} 2023-06-28 12:10:48 : > Received 36 bytes 2023-06-28 12:10:48 : > Event data { "jsonrpc": 2, "result": [], "id": 2 } ! No response data received?
00:00:00.781 [Unknown] MailGraph notification failed : SyntaxError: invalid json (at offset 10)

While running php mailGraph.php test gives:

root@driftzabbix:/usr/share/zabbix# php mailGraph.php test
2023-06-28 10:14:59 : # Configuration taken from config.json
{
    "script_baseurl": "https:\/\/driftzabbix.intern.company.no\/",
    "cli_itemId": 0,
    "cli_triggerId": 0,
    "cli_eventId": 0,
    "cli_duration": 0,
    "cli_recipient": "driftzabbix@company.no",
    "cli_subject": "[TEST] {{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}",
    "cli_baseURL": "https:\/\/driftzabbix.intern.company.no\/zabbix\/",
    "cli_period": "30m",
    "cli_period_header": "Last 30 minutes",
    "cli_debug": 1,
    "cli_proxy": "",
    "zabbix_user": "<masked>",
    "zabbix_user_pwd": "<masked>",
    "zabbix_api_user": "<masked>",
    "zabbix_api_pwd": "<masked>",
    "mail_from": "driftzabbix@company.no",
    "subject": "{{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}",
    "smtp_server": "localhost",
    "smtp_port": 25,
    "smtp_transport": "none",
    "smtp_strict": "yes",
    "graph_match": "any",
    "period": "20m",
    "period_header": "Last 20 minutes",
    "debug": 0
}
2023-06-28 10:14:59 : <<< mailGraph v2.020 >>>
2023-06-28 10:14:59 : # Invoked from CLI
2023-06-28 10:14:59 : # Data passed to MailGraph main routine and used for processing
{
    "itemId": 0,
    "eventId": 0,
    "recipient": "driftzabbix@company.no",
    "baseURL": "https:\/\/driftzabbix.intern.company.no\/zabbix\/",
    "duration": 0,
    "subject": "[TEST] {{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}",
    "period": "30m",
    "period_header": "Last 30 minutes",
    "debug": 1,
    "HTTPProxy": ""
}
2023-06-28 10:14:59 : # LOGIN to Zabbix
2023-06-28 10:14:59 : % postJSON: https://driftzabbix.intern.company.no/zabbix/api_jsonrpc.php
2023-06-28 10:14:59 : > POST data: {"jsonrpc":"2.0","method":"user.login","params":{"user":"<masked>","password":"<masked>"},"id":1,"auth":null}
2023-06-28 10:15:00 : > Received 68 bytes
2023-06-28 10:15:00 : > Token = 217019ece42aca75b865126d9ee83d47
2023-06-28 10:15:00 : # Retreiving EVENT information
2023-06-28 10:15:00 : % postJSON: https://driftzabbix.intern.company.no/zabbix/api_jsonrpc.php
2023-06-28 10:15:00 : > POST data: {"jsonrpc":"2.0","method":"event.get","params":{"eventids":0,"output":"extend","selectRelatedObject":"extend","selectSuppressionData":"extend"},"auth":"217019ece42aca75b865126d9ee83d47","id":2}
2023-06-28 10:15:00 : > Received 36 bytes
2023-06-28 10:15:00 : > Event data
{
    "jsonrpc": 2,
    "result": [],
    "id": 2
}
! No response data received?

**Comment by moudsen** [comment]
I've scanned quickly through the given Zabbix reference which pointed me to a related change Zabbix has introduced since version 5.x which I was not aware of by changing "user" to "username" for the user.login API call.

I'm testing currently in my own environment and will revert back to you with the solution for it as it feels as only the variable name change from "user" to "username" should do the trick ...

**Comment by moudsen** [comment]
mailGraph.php line #630

Change 'user' to 'username' and this should resolve your issue. Tested in 6.0 LTS.
Related change by Zabbix with details found at https://support.zabbix.com/browse/ZBX-22120

Will test shortly in an actual 6.4 environment to verify. Changing it to "username" will make the code compatible with Zabbix 5, 6.0 and 6.4+.

Can you please verify at your end?

```
$request = array('jsonrpc'=>'2.0',
                     'method'=>'user.login',
                     'params'=>array('user'=>$z_api_user,
                                     'password'=>$z_api_pass),
                     'id'=>nextRequestID(),
                     'auth'=>null);
```

```
$request = array('jsonrpc'=>'2.0',
                     'method'=>'user.login',
                     'params'=>array('username'=>$z_api_user,
                                     'password'=>$z_api_pass),
                     'id'=>nextRequestID(),
                     'auth'=>null);
```

**Comment by moudsen** [comment]
Tested in 5.4 legacy environment. Confirmed working.

**Comment by moudsen** [comment]
The "hack" you are referring to is for Grafana and most likely a lot of other applications as well that still use "user" as the parameter for the user.login API call. It's similar to the fix I've proposed above be it that I'm coding in PHP hence it's easier (no compilation required).
Your reasoning that the username variable should be changed was very correct though :-).

**Comment by moudsen** [comment]
Preparing for next release including some other minor code updates as well that have arised from other issues and suggestions.

**Comment by pqvindesland** [comment]
I changed it so it now looks like this:
    $request = array('jsonrpc'=>'2.0',
                    'method'=>'user.login',
                     'params'=>array('username'=>$z_api_user,
                                    'password'=>$z_api_pass),
                     'id'=>nextRequestID(),
                     'auth'=>null);

But it doesn't seem to make any difference when I run php mailGraph.php test

root@driftzabbix:/usr/share/zabbix# php mailGraph.php test
2023-06-29 14:30:20 : <<< mailGraph v2.020 >>>
2023-06-29 14:30:20 : # Invoked from CLI
2023-06-29 14:30:20 : # Data passed to MailGraph main routine and used for processing
{
    "itemId": 0,
    "eventId": 0,
    "recipient": "driftzabbix@fremtind.no",
    "baseURL": "https:\/\/driftzabbix.intern.fremtind.no\/zabbix\/",
    "duration": 0,
    "subject": "[TEST] {{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}",
    "period": "30m",
    "period_header": "Last 30 minutes",
    "debug": 1,
    "HTTPProxy": ""
}
2023-06-29 14:30:20 : # LOGIN to Zabbix
2023-06-29 14:30:20 : % postJSON: https://driftzabbix.intern.fremtind.no/zabbix/api_jsonrpc.php
2023-06-29 14:30:20 : > POST data: {"jsonrpc":"2.0","method":"user.login","params":{"username":"<masked>","password":"<masked>"},"id":1,"auth":null}
2023-06-29 14:30:21 : > Received 68 bytes
2023-06-29 14:30:21 : > Token = cc52a41ae5152a1d220d40042d368562
2023-06-29 14:30:21 : # Retreiving EVENT information
2023-06-29 14:30:21 : % postJSON: https://driftzabbix.intern.fremtind.no/zabbix/api_jsonrpc.php
2023-06-29 14:30:21 : > POST data: {"jsonrpc":"2.0","method":"event.get","params":{"eventids":0,"output":"extend","selectRelatedObject":"extend","selectSuppressionData":"extend"},"auth":"cc52a41ae5152a1d220d40042d368562","id":2}
2023-06-29 14:30:21 : > Received 36 bytes
2023-06-29 14:30:21 : > Event data
{
    "jsonrpc": 2,
    "result": [],
    "id": 2
}
! No response data received?


Media type test log
00:00:00.000 [Debug] [MailGraph Webhook] Sending request: https://driftzabbix.intern.fremtind.no/mailGraph.php?{"itemId":"{ITEM.ID}","eventId":"{EVENT.ID}","recipient":"{ALERT.SENDTO}","baseURL":"https://driftzabbix.intern.fremtind.no/","duration":"{EVENT.DURATION}","graphWidth":"300","graphHeight":"120","subject":"{{ HOST_NAME|raw }}: ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}","showLegend":"0","periods":"10m,4h,1d,7d","periods_headers":"Last 10 minutes,Last 4 hours,Last day,Last 7 days","infoTest":"Test"}
00:00:00.713 [Debug] [Mailgraph Webhook] Receiving response:! No response data received?
00:00:00.713 [Unknown] MailGraph notification failed : SyntaxError: invalid json (at offset 1)

Zabbix 6.0.18 is still the version that I am running 

Any idea?

**Comment by pqvindesland** [comment]
Also isn't the CurlHttpRequest now HttpRequest since 5.4 and is now depreciated? https://www.zabbix.com/documentation/current/en/manual/config/items/preprocessing/javascript/javascript_objects 

But if I edit it to

`    params = JSON.parse(value),
        req = new HttpRequest(),
        fields = {},
        resp = '',
        result = { tags: {} };`

And run a test then I get error "00:00:00.000 [Unknown] MailGraph notification failed : TypeError: undefined not callable (property 'AddHeader' of [object Object])" 

I´m just throwing out ideas here :)

**Comment by moudsen** [comment]
You're ahead of my distribution. LOL.

Yes, that one also needs to be changed in order to work - hence my intention to test on 6.4 in one of my production environments that shortly needs to have mailGraph installed. I did not have a 6.4 to my disposal beforehand :-(.

**Comment by moudsen** [comment]
n order for the TEST routine to work you need a valid EVENT_ID specified in the configuration that is taken from Zabbix from for example the events overview.

The login works just fine now as a token from Zabbix was obtained. That was the main objective to get mailGraph running again for you :-).

2023-06-29 14:30:21 : > **Token = cc52a41ae5152a1d220d40042d368562**

Below tells me that the configuration does not have a test event id reference:

2023-06-29 14:30:21 : > POST data: {"jsonrpc":"2.0","method":"event.get","params":{**"eventids":0**,"output":"extend","selectRelatedObject":"extend","selectSuppressionData":"extend"},"auth":"cc52a41ae5152a1d220d40042d368562","id":2}

If you specifiy an event id this will start to function for you as with that reference the calls will pick up related items as well as the associated host(s).

Let me know if that works for you?

**Comment by moudsen** [comment]
Issue #32 also need to be incorporated to make 6.4 work - bringing together the pieces ...

**Comment by moudsen** [comment]
https://github.com/moudsen/mailGraph/wiki/8--Troubleshooting
Half way there is a description of the required parameters to make the testing possible.

**Comment by pqvindesland** [comment]
Yeah many thanks I got it working, I hate it when it's that obvious and I can't see it.

As far as I can see it's all working now, tests and my simple alert that I can set off when needed together with the resolve alert :)

Again many thanks for taking the time assisting me.

Regards
Per

**Comment by moudsen** [comment]
You're welcome. I am still working on a next release to combine all the updates.
Also appreciate your patience and the questions that will further improve mailGraph!
Will notify here when the new package has been released (it will contain instructions what to replace and what has changed).

**Comment by moudsen** [comment]
Releasing in a few minutes from now
