### ISSUE TITLE
Reinstall twig and phpmailer after a reboot

### ISSUE THREAD

**Issue by pqvindesland** [moudsen/mailGraph#43]
Hi 

Just a quick question, I notice that after each reboot mailgraph fails, I figured out that i needed to install twig and phpmailer, is that something that you are seeing also? 

It's an easy fix, I have added "@reboot cd /usr/share/zabbix && composer require phpmailer/phpmailer -n && composer require twig/twig -n" to crontab so this is more of a quriosity then anything else.

Regards
Per

**Comment by moudsen** [comment]
Hi Per,

At first I could not understand how this could happen, but your reboot command kind of gives it away.
It may even be related to your previous issue where you had to re-install before things started to work again ...

Principal statement:

_the /use/share/zabbix is maintained by the package manager (!)_

... and should therefor never be changed at its source location, for example by adding or changing code, as its contents may get overwritten by package manager activities, such as (re)install, updates and upgrades.

Any 'custom' changes or code made at that location may/will get overwrriten!

In case of using a package manager for Zabbix or other web server applications directly from a repository requires a special handler to attach the zabbix code to one or more web host configurations.

Although your reboot approach may work for now, I'm 100% certain that any package manager activity afterwards will also cause the service to cease or show weird behavior (an upgrade to a newer version of Zabbix will definitely wipe the existing directory before installing the new code).

Most web servers hence have the "alias" function where code, external to the virtual host configuration, is linked into an actual site, which will allow for a mixture of "Zabbix" and "others" on the same domain name.

For example the Apache virtual host configuration gist I have in place (fictive domain name):

```
<VirtualHost *:443>
  ServerName myzabbix.puzzl.nl
  DocumentRoot /var/www/vhosts/myzabbix.puzzl.nl

  Alias /zabbix /usr/share/zabbix

  <Directory "/usr/share/zabbix">
    Options FollowSymlinks
    AllowOverride All
  </Directory>

  <Directory "/var/www/chosts/myzabbix.puzzl.nl/config">
    Require all denied
  </Directory>
</VirtualHost>
```

So, "https://myzabbix.puzzl.nl/zabbix" will serve Zabbix from /usr/share/zabbix while "https://myzabbix.puzzl.nl" picks up from /var/www/vhosts/myzabbix.puzzl.nl.

In this way Zabbix code is pulled from the package manager location while mailGraph (and its dependencies) is served from an actual www related directory.

If you wish to keep Zabbix where it is today (at a website root location, in my example case "https://myzabbix.puzzl.nl") you could create another website and another domainname ("https://mailgraph.puzzl.nl") and put mailGraph etc. in that directory and adjust the mailGraph configuration accordingly.

If after this long response it appears I'm wrong in my reasoning happy to assist to ensure you are working from a persistent location for mailGraph :-).

Short message: **do not install mailGraph in /usr/share/zabbix** ... (!)

When this is actually the case with you I will update my wiki accordingly to warn other users who may encounter the same struggle as you have right now.

Kind regards, Mark

**Comment by pqvindesland** [comment]
Yeah it's on my list for Zabbix 7, I really need to go through the whole setup when 7 comes out, I was also afraid that any updates of Zabbix would wipe any configs but anything that I have in /usr/share/zabbix that is not in the Zabbix installation remains so nothing has so far been overwritten.

Zabbix 7 will be installed on a different distribution that is in line with the corporate requirements (politically correct said :)) 

But it's a less than perfect setup, more of a that will do for the moment :)  

Many thanks for clarifying and the examples, I will keep this in mind when I start the move to the new machine.

Regards
Per

**Comment by moudsen** [comment]
Happy to assist. Closing the issue now while I will put some of the stuff published here om the Wiki at a later moment.
Regards, Mark
