### ISSUE TITLE
Incorrect display of international characters in the report

### ISSUE THREAD

**Issue by dima-online** [moudsen/mailGraph#45]
I get a response from api_jsonrpc.php  
`POST data: {"jsonrpc":"2.0","method":"host.get","params":{"hostids":"11285","output":"extend","selectTags":"extend"},"auth":"4acfd9a31afba53f10a7fea3625b1d42","id":6}`

"name": "\u0413\u043b\u0430\u0432\u043d\u044b\u0439 \u0441\u0435\u0440\u0432\u0435\u0440 \u043c\u043e\u043d\u0438\u0442\u043e\u0440\u0438\u043d\u0433\u0430"

Twig will encode it in UTF-8 (in default) again. As a result, I receive a letter with the subject "Ð“Ð»Ð°Ð²Ð½Ñ‹Ð¹ ÑÐµÑ€Ð²ÐµÑ€ Ð¼Ð¾Ð½Ð¸Ñ‚Ð¾Ñ€Ð¸Ð½Ð³Ð°"

It is necessary to add to the script code for correct operation
```
$mail->CharSet = "UTF-8";
$mail->Encoding = "base64";

```
The specified name should be displayed as "Главный сервер мониторинга".

**Comment by moudsen** [comment]
Thank you for your valued response - I will update mailGraph shortly and include your recommended update
Kind regards, Mark

**Comment by moudsen** [comment]
Code updated in v2.17.
