### ISSUE TITLE
CUSTOM information are not passed to TWIG / Template

### ISSUE THREAD

**Issue by BernhardLinz** [moudsen/mailGraph#47]
I can see in the log that the informations are passed to the `mailGraph.php`:<br>
```
2024-11-20 14:38:05 : # Data passed to MailGraph main routine and used for processing
{
    "itemId": null,
    "eventId": 86,
    "recipient": "bernhard@znil.de",
    "baseURL": "http:\/\/192.168.0.6\/",
    "duration": null,
    "graphWidth": 600,
    "graphHeight": 300,
    "subject": "{{ HOST_NAME|raw }}: ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}",
    "showLegend": 1,
    "periods": "7d,183d",
    "periods_headers": "Letzten 7 Tage,Letzten 6 Monate",
    "infoActionName": "Test Action",
    "infoTest": "Test"
}
```
The last two. But at the end of the log in the section **=== VALUES AVAILABLE FOR TWIG TEMPLATE ===** these Vaules ar missing.

The reason ist that at line 627 to 630 the values are proccessed:
```
    foreach($problemData as $aKey=>$aValue)
    {
        if (substr($aKey,0,4)=='info') { $mailData[$aKey] = $aValue; }
    }
```
but in Line 743 the array is deleted:
```
    $mailData = array();
```
So just comment out this line or move it before line 627

**Comment by moudsen** [comment]
That's definitely a bug. Thank you for providing me the update and the fix.
I will take this forward into my next release (on short notice).
Thank you!
Kind regards, Mark

**Comment by moudsen** [comment]
Moved it up to the initialization section.
